# define DWM_BORDERPX 1
# define DWM_SNAP 32
# define DWM_SHOWBAR 1
# define DWM_TOPBAR 1
# define DWM_FONT {"monospace:size=10"}
# define DWM_FOREGROUND "#93a1a1"
# define DWM_BACKGROUND "#111111"
# define DWM_BORDER "#93a1a1"
# define DWM_SELFOREGROUND "#073642"
# define DWM_SELBACKGROUND "#4c83ff"
# define DWM_SELBORDER "#cb4b16"
